
version: "2.1"
services:

  jenkins-master:
    build: .
    ports:
      - "8080:8080"
      - "50000:50000" #only for JNLP
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - 133 #docker group id

volumes:
    jenkins_home: